Patch: update Splitio package version
splitio/redux-client pull request #32
Opened 2021-04-28 18:33 UTC by emilianofant-split

# Redux SDK

## What did you accomplish?
Update Split SDK version to catch up with the latest changes.

## How do we test the changes introduced in this PR?

## Extra Notes

2021-04-28 18:59 UTC, NicoZelaya approved these changes

2021-04-28 20:21 UTC, EmilianoSanchez requested changes

2021-04-28 20:21 UTC, EmilianoSanchez commented on CHANGES.txt
> +1.3.2 (April 28, 2021)
keep only one new entry in the changelog:

```
 1.3.1 (April 28, 2021)
 - Updated Split's JS SDK and other dependencies to fix vulnerabilities.
```

2021-04-28 20:21 UTC, EmilianoSanchez commented on package.json
> +  "version": "1.3.2",
the new patch version should be `1.3.1`

2021-04-28 20:21 UTC, EmilianoSanchez commented on package.json
> +    "@splitsoftware/splitio": "^10.15.4"
if we are releasing JS SDK first. we could update it to `^10.15.5`

2021-04-29 15:19 UTC, EmilianoSanchez approved these changes

2021-04-29 15:19 UTC, merged